### ISSUE TITLE
Fable.Reaction needs a logo

### ISSUE THREAD

**Issue by dbrattli** [dbrattli/Reaction#6]
Reaction/Fable.Reaction needs a logo. Perhaps something a mix or combo of the dragon and the electric eel? Do we need a separate logo for Reaction and Fable.Reaction, or could we have the same?
(https://github.com/dbrattli/Reaction/issues/9)

Check out: 

- Fable logo: https://github.com/fable-compiler/Fable/issues/969
- Rx logo: https://github.com/dotnet/reactive/tree/master/Rx.NET/Resources/Artwork
- FSharp.Control.Reactive: http://fsprojects.github.io/FSharp.Control.Reactive/

**Comment by alfonsogarciacaro** [comment]
@whitetigle Just in case you want to have a look, the Affinity Designer file is [here](https://github.com/fable-compiler/fable-compiler.github.io/tree/new-site/art)

**Comment by dbrattli** [comment]
They are dancing ❤

**Comment by sergey-tihon** [comment]
My wife did one option 

### Option 2

![rxv2](https://user-images.githubusercontent.com/1197905/47957361-5efd2580-dfc5-11e8-8484-248e135c8151.jpg)

### Option 3

![rxv3](https://user-images.githubusercontent.com/1197905/47957362-6290ac80-dfc5-11e8-9c33-aab9d5701d6b.jpg)

**Comment by alfonsogarciacaro** [comment]
Looks good @sergey-tihon! You gave an idea for another proposal, what about something along these lines?

![fable reaction](https://user-images.githubusercontent.com/8275461/47958640-18acc400-dfcf-11e8-828b-7c9a8b96e0ea.png)

**Comment by dbrattli** [comment]
@sergey-tihon please say thanks to your wife from me. This is great and could actually solve 2 problems:

- **Option 2** looks like [Reaction](https://github.com/dbrattli/reaction). Reaction is the core tech behind Fable.Reaction and basically just plain Async Rx. But it's F# and carefully written to work with Fable. But Reaction runs anywhere, .NET, Fable (Node, Web) so it makes sense to me that the logo for Reaction is Rx red.
- **Option 3** looks like Fable.Reaction. Fable.Reaction is the specific use of Reaction within Fable and Elmish. Thus it's much more on the Fable side than Reaction, and it makes sense to me that the logo for Fable.Reaction is Fable blue.

**Comment by sergey-tihon** [comment]
I like Option 3, but i think that it can be hard to recognize the difference in logo between `Fable.Reaction` and `Fable`, when logo completely in the same color schema.

I think that we should consider options with Rx color (at least somewhere) like option 8

### Option 8

![rxv8](https://user-images.githubusercontent.com/1197905/47961524-bd55f280-e01d-11e8-8375-f8e3ce202318.jpg)

**Comment by dbrattli** [comment]
Yes, we could use the Rx color in the Logo of Fable.Reaction. Note also that in option 8 you are using the dragon head while option 3 uses the eel. If you want to separate it more with the Fable logo then we could use Rx colors for both, but have eel head on Reaction and dragon head on Fable.Reaction.

**Comment by sergey-tihon** [comment]
And only now I realized that you need two logos! 
Could you please try these two in gitbook.

### Reaction
![rx](https://user-images.githubusercontent.com/1197905/47962250-1ed08e00-e02b-11e8-8f6c-eac509383821.jpg)

### Fable.Reaction
![frx](https://user-images.githubusercontent.com/1197905/47962252-23954200-e02b-11e8-8c29-d50d27e0a2fb.jpg)

**Comment by sergey-tihon** [comment]
And only now I realized that you need two logos! 
Could you please try these two in gitbook.

### Reaction
![rx](https://user-images.githubusercontent.com/1197905/47962250-1ed08e00-e02b-11e8-8f6c-eac509383821.jpg)

### Fable.Reaction
![frx](https://user-images.githubusercontent.com/1197905/47962252-23954200-e02b-11e8-8c29-d50d27e0a2fb.jpg)

**Comment by dbrattli** [comment]
This is much better now. Should I get a tatoo!?

<img width="1226" alt="skjermbilde 2018-11-04 kl 10 25 16" src="https://user-images.githubusercontent.com/849479/47962364-0d33ba00-e01c-11e8-9f11-145e2f376118.png">
<img width="1036" alt="skjermbilde 2018-11-04 kl 10 30 15" src="https://user-images.githubusercontent.com/849479/47962415-baa6cd80-e01c-11e8-9547-aa3e9a7fff68.png">

**Comment by sergey-tihon** [comment]
> This is much better now. Should I get a tatoo!?

Tatoo is up to you ;) 

I like these options because:
- they looks unique
- they similar to each and show relation between project
- reaction version clearly similar to Rx
- fable.reaction clearly similar to Fable

**Comment by dbrattli** [comment]
Just testing the logos together with the gitbook documentation to get a better feeling of how they would look. Fable.Reaction looks great. Could perhaps have Rx colour on top part as well to separate more from Fable logo!? Unsure about Reaction. It would be cool if we should try the Rx shape (curled together) but with the dragon head, i.e a curled Fable dragon with Rx colors!?

<img width="1001" alt="skjermbilde 2018-11-04 kl 09 35 06" src="https://user-images.githubusercontent.com/849479/47961958-208f5700-e015-11e8-9594-993209c3e514.png">
<img width="867" alt="skjermbilde 2018-11-04 kl 09 34 34" src="https://user-images.githubusercontent.com/849479/47961960-2422de00-e015-11e8-96c7-63d9b61cf863.png">

**Comment by dbrattli** [comment]
I really like them. Do you want to make a PRs to a `/logo` directory for each project. I'm going to need a `.png` version for the documentation. (not sure why one of my previous postings is stuck at the bottom of the discussion. Bug in github perhaps).

**Comment by alfonsogarciacaro** [comment]
@dbrattli This is not exactly a topic for this issue, but how different are Reaction and Fable.Reaction? Is Reaction the base for Fable.Reaction, or one targets .NET while the other targets Fable? Do they have the same API?

I'm a bit concerned that having the two projects with different logos can be a bit confusing for the users. My suggestion would be to keep/promote a single project/repo (also unifying documentation) and use it to generate different packages for .NET/Fable. If Reaction is the base, and Fable.Reaction is just a way to apply to Elmish it may make sense to change the name to Elmish.Reaction.

For reference, [Elmish itself dropped the Fable prefix in the project name](https://github.com/elmish/elmish/issues/145) when it started to be applied in other platforms (like Xamarin) but it still keeps the Fable.Elmish packages specifically targeting the browser. [Thoth.Json](https://mangelmaxime.github.io/Thoth/json/v2/net.html) is another example of a project that provides an API compatible with both .NET/Fable for easy code interop but has different packages depending on the platform.

> BTW, it could be possible to have only one package and just use `#if FABLE_COMPILER` directives where Fable-specific code is needed (this is possible because Fable packages include the sources), but it may be easier to maintain two different packages.

**Comment by dbrattli** [comment]
@alfonsogarciacaro Yes, Reaction is the base for Fable.Reaction, so I see your point that it can be confusing for users with the 2 different projects. 

- Reaction is similar to [Control.Observable](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/control.observable-module-%5Bfsharp%5D) only that it adds an `Async` dimension, is dependency free and works with Fable. You can use it with ASP.NET Core, Giraffe for server side stream processing.
- Fable.Reaction is most of all a Reactive-MVU specific architecture that hooks into Elmish, but you then use Reaction directly to do the actual transformation of the message stream. It adds a couple of Fable specific operators such as `ofPromise`, `ofMouseMove` and `msgChannel`. 

So it might make sense to make this into one single project with 2 NuGet packages. `Reaction` and `Fable.Elmish.Reaction`. I'm no fan of `#if FABLE_COMPILER` since it confuses Ionide (`#if !FABLE_COMPILER` works better).

Reaction could probably be used with Xamarin also, but have never tried it. Then it could be called `Elmish.Reaction` if we made an assembly without the Fable specific operators.

**Comment by dbrattli** [comment]
@alfonsogarciacaro But you could also argue that Reaction is to Fable(.Elmish).Reaction what RxJS is to Angular. Thus it could be that Fable.Reaction belongs with Elmish (https://github.com/elmish ) and should be moved there, but I haven't talked with Eugene so I don't know what he thinks of Fable/Reaction. Reaction might be moved to ReactiveX (http://reactivex.io/). Perhaps Reaction should be renamed to something Rx'ish to avoid confusion, FSharp.AsyncRx?

Thus we might want just want to keep the projects separate from now until we see how it goes.

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm still afraid that having two projects with similar names (and very similar logos) is going to be confusing for the users (we had a [similar discussion for Elmish.Remoting](https://github.com/SAFE-Stack/SAFE-BookStore/pull/342#issuecomment-398181616)). For example, in the first page of the Reaction documentation it says it's designed with Fable in mind, but then users discover there's another package named Fable.Reaction. The difference may not be immediately obvious.

I would suggest:

- If you want to focus on Fable/SAFE for now, try to unify the projects somehow. Maybe not putting them in the same repo, but unifying the documentation and having just one logo.
- If you want to keep Reaction in the Rx family, it's probably a good idea to change the name to something like `FSharp.AsyncRx` as you suggest, reduce the references to Fable in the documentation (just say it's compatible with Fable but can be used in .NET projects too) and don't have a logo that explicitly references Fable.

In both cases, I'd rename Fable.Reaction to `Elmish.Reaction` and keep the logo from [this comment](https://github.com/dbrattli/Fable.Reaction/issues/6#issuecomment-435653796) which is tremendously cool :clap: :clap:

**Comment by alfonsogarciacaro** [comment]
BTW @sergey-tihon Is there any special tool you use for reshaping the SVG (the tail of the Rx eel) or you just move/rotate the curve points?

**Comment by dbrattli** [comment]
@alfonsogarciacaro Refactoring as we speak 😄 The structure I'm going for is:

1) **Reaction** will be deleted

2) **Fable.Reaction** will be renamed to **Reaction** and contain the following dirs and packages:
  - **AsyncRx** (Reaction.AsyncRx.x.y.z.nupkg)
  - **Elmish** (Elmish.Reaction.x.y.z.nupkg), for use with Elmish without Fable
  - **Fable.Elmish** (Fable.Elmish.Reaction.x.y.z.nupkg), for use with Elmish and Fable

Docs will then be merged. Will this be OK?

**Comment by alfonsogarciacaro** [comment]
Sounds great, thank you!

**Comment by sergey-tihon** [comment]
> BTW @sergey-tihon Is there any special tool you use for reshaping the SVG (the tail of the Rx eel) or you just move/rotate the curve points?

I am just proxy in this case, i tell my wife what we need, what meaning we want to put in logo and what visual we expect. She give me image in the format that I asked ❤️.  But as I know she draw it by hand in Adobe Illustrator.

**Comment by alfonsogarciacaro** [comment]
Great, thank your wife on our behalf! 🏅
